version: '3'
services:
  php:
    container_name : php
    build : ./php
    volumes:
      - ./public_html:/var/www/html
    working_dir: /var/www/html
    
  nginx:
    container_name: nginx
    image: nginx:1.19.5-alpine
    ports:
      - 8888:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./public_html:/var/www/html
    depends_on:
      - php

  sqlite3:
    container_name: sqlite
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - ./public_html/:/root/db/
